conteudo/urls.py
from django.urls import path
from conteudo import views

app_name = 'conteudo'

urlpatterns = [
    path('', views.exibir_catalogo, name='catalogo'),
    path('cadastro_video/', views.cadastro_video, name='cadastro_video'),
    path('editar_video/<int:id>/', views.editar_video, name='editar_video'),
    path('<int:id>/', views.exibir_video, name='exibir_video'),

    path('categoria/', views.lista_categoria, name='listar_todas_categorias'),
    path('categoria/<int:id>/', views.lista_categoria, name='lista_categoria'),
]

login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('', views.pagina_login, name='pagina_login'),
]

projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from projeto import views, settings

app_name = 'projeto'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.pagina_inicial, name='pagina_inicial'),
    path('conteudo/', include('conteudo.urls')),
    path('login/', include('login.urls')),
]

# Necessário para upload de video
# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastro/models.py
from django.db import models

# Create your models here.

conteudo/models.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=200)

    class Meta:
        ordering = ('nome',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nome

    def videosCategoria(self):
        return Video.objects.all().filter(categoria_id=self.id).order_by('-id')[:4]

class Video(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=255)
    url = models.FileField(upload_to='conteudo/videos/')
    capa = models.FileField(upload_to='conteudo/images/')
    visualizacao = models.DecimalField(max_digits=10, decimal_places=1, default=0)
    nota = models.FloatField(max_length=20)
    sinopse = models.CharField(max_length=500)

    class Meta:
            ordering = ('nome',)
            verbose_name = 'video'
            verbose_name_plural = 'videos'

    def __str__(self):
        return self.nome

login/models.py
from django.db import models

# Create your models here.

conteudo/forms.py
from django import forms

from conteudo.models import Video, Categoria


class VideoForm(forms.ModelForm):
    error_messages = {
        'campo invalido' : "Campo inválido"
    }

    class Meta:
        model = Video
        fields = ('video_id','categoria', 'nome', 'url', 'capa', 'visualizacao', 'nota', 'sinopse')

    video_id = forms.CharField(widget=forms.HiddenInput(), required=False)

    categoria = forms.ModelChoiceField(
        error_messages={'required': 'Campo obrigatório', },
        queryset=Categoria.objects.all().order_by(id),
        empty_label='--- Selecionar a Categoria ---',
        widget=forms.Select(attrs={'class': 'form-control form-control-sm'}),
        required=True
    )

    nome = forms.CharField(
        error_messages = {'required', 'Campo obrigatório',},
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True
    )

cadastro/views.py
from django.shortcuts import render

# Create your views here.

conteudo/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404

from conteudo.models import Video, Categoria

def exibir_catalogo(request):
    categorias = Categoria.objects.all()
    return render(request, 'conteudo/catalogo_videos.html', {'categorias': categorias})

def cadastro_video(request):
    return  render(request, 'conteudo/cadastro_video.html')

def editar_video(request):
    return render(request, 'conteudo/editar_video.html')

def lista_categoria(request, id=None):
    categorias = Categoria.objects.all()
    if id != None:
        videos_lista = Video.objects.all().filter(categoria_id=id)
    else:
        videos_lista = Video.objects.all()

    paginator = Paginator(videos_lista, 3)
    page = request.GET.get('page',1)

    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)

    return render(request, 'conteudo/lista_categoria.html', {'categorias': categorias, 'videos' : videos})

def exibir_video(request, id):
    video = get_object_or_404(Video, id= id)
    categorias = Categoria.objects.all()
    return render(request, 'conteudo/player_video.html', {'video':video, 'categorias':categorias})

login/views.py
from django.shortcuts import render

def pagina_login(request):
    return render(request, 'login/pagina_login.html')

projeto/views.py
from django.shortcuts import render

def pagina_inicial(request):
    return render(request, 'index.html')

conteudo/templates/conteudo/cadastro_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

conteudo/templates/conteudo/catalogo_videos.html
{% extends "base.html" %}

{% load static %}

{% block titulo %} Meu Canal - Início {% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="{% url 'conteudo:catalogo' %}">Meu Canal</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
				  <li class="nav-item active">
				    <a class="nav-link" href="{% url 'conteudo:catalogo' %}">Início <span class="sr-only">(current)</span></a>
				  </li>
	  			  <li class="nav-item">
				    <a class="nav-link" href="#">Séries</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href="#">Área Kids</a>
				  </li>
	  			  <li class="nav-item">
				    <a class="nav-link" href="#" type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">Categorias</a>
				  </li>
				</ul>
				<form class="form-inline my-2 my-lg-0 ml-auto">
				  <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Search">
				  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
				</form>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          Usuário
          			      <img class="rounded-circle" src="{% static 'projeto/images/user_male.png' %}" alt="Generic placeholder image" width="55" height="50">
				        </a>
				        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
				          <a class="dropdown-item" href="#">Minha Conta</a>
				          <a class="dropdown-item" href="#">Minha Lista</a>
				          <div class="dropdown-divider"></div>
				          <a class="dropdown-item" href="{% url 'pagina_inicial' %}">Logout</a>
				        </div>
			      	</li>
			  	</ul>
			</div>
		</div>
	</nav>
{%  endblock %}

{% block conteudo %}
	<div id="botaoMover" class="carousel slide botao_play mb-3" data-ride="carousel">
	  <div class="carousel-inner">
	    <div class="carousel-item active">
	      <img class="d-block w-100" src="images/stranger-things-2.jpg" alt="Stranger Things 2">
  	      <div class="carousel-caption">
	      	<a href="video.html"><h1 class="oi oi-play-circle"></h1></a>
		  </div>
	    </div>
	    <div class="carousel-item">
	      <img class="d-block w-100" src="images/la_casa_de_papel.jpg" alt="La Casa de Papel">
	      <div class="carousel-caption">
	      	<a href="video.html"><h1 class="oi oi-play-circle"></h1></a>
		  </div>
	    </div>
	    <div class="carousel-item">
	      <img class="d-block w-100" src="images/gotham.jpg" alt="Gotham">
  	      <div class="carousel-caption">
	      	<a href="video.html"><h1 class="oi oi-play-circle"></h1></a>
		  </div>
	    </div>
	  </div>
	  <a class="carousel-control-prev" href="#botaoMover" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#botaoMover" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>

	<div class="container">
		<nav class="d-none d-md-block">
		  <div class="nav nav-tabs" id="nav-tab" role="tablist">
		    <a class="nav-item nav-link active white" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Continue assistindo</a>
		    <a class="nav-item nav-link white" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Lista de favoritos</a>
		  </div>
		</nav>
		<div class="tab-content mb-5 rolagem d-none d-md-block" id="nav-tabContent">
		  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
		  	<ul class="list-group">
			  	<li class="list-group-item">
				  	<a href="video.html">Black Mirror</a>
				  	<div class="progress">
	 				 <div class="progress-bar" role="progressbar" style="width: 75%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75%</div>
					</div>
			    </li>
			  	<li class="list-group-item">
				  	<a href="video.html">Stranger Things</a>
				  	<div class="progress">
	 				 <div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
					</div>
			    </li>
			  	<li class="list-group-item">
				  	<a href="video.html">Gotham</a>
				  	<div class="progress">
	 				 <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
					</div>
			    </li>
			</ul>
		  </div>
		  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
		  	<ul class="list-group">
			  <li class="list-group-item"><a href="video.html">La Casa de Papel</a></li>
			  <li class="list-group-item"><a href="video.html">Prison Break</a></li>
			  <li class="list-group-item"><a href="video.html">Jumanji</a></li>
			  <li class="list-group-item"><a href="video.html">Velozes e Furiosos 5</a></li>
			  <li class="list-group-item"><a href="video.html">Transformers</a></li>
			</ul>
		  </div>
		</div>

		<div class="selecao_videos">
			{% for categoria in categorias %}
                <div class="mb-2 row area_escolha">
                    <div class="col-md-6">
                        <h3>{{ categoria.nome }}</h3>
                    </div>
                    <div class="col-md-6 d-none d-md-block">
                        <a href="{% url 'conteudo:lista_categoria' id=categoria.id %}">
                            <button type="button" class="btn btn-dark float-right">Todos os videos da categoria >></button>
                        </a>
                    </div>
                </div>
			    <div class="card-group mb-4">
			  	    <div class="row">
                        {% for video in categoria.videosCategoria %}
                            <div class="col-md-3 mb-2">
                              <div class="card">
                                <img class="card-img-top" src="{{video.capa}}" alt="{{ video.nome }}">
                                <div class="card-body">
                                  <h5 class="card-title " data-toggle="tooltip" data-placement="top" title="{{ video.nome }}">{{ video.nome }}</h5>
                                  <p class="card-text">
                                        <ul class="list-unstyled">
                                            <li>Nota: {{ video.nota }}</li>
                                            <li>Sinopse: <a tabindex="0" data-trigger="focus"
                                                   data-toggle="popover"
                                                   data-title="{{ video.nome }}"
                                                   data-placement="top"
                                                   data-content="{{ video.sinopse }}">Clique Aqui</a></li>
                                        </ul>
                                    <a href="{% url 'conteudo:exibir_video' id=video.id %}" type="button" class="btn btn-info btn-block">Assistir</a>
                                  </p>
                                </div>
                              </div>
                            </div>
                        {% endfor %}
                    </div>
				    <div class="col-md-12 mb-4 d-block d-sm-none">
					    <button type="button" class="btn btn-dark d-block">Todos os videos da categoria >></button>
				    </div>
			    </div>
            {% endfor %}
	    </div>
    </div>
{% endblock %}

{% block modal-content %}
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Categorias</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group">
            {% for categoria in categorias %}
                <a href="{% url 'conteudo:lista_categoria' id=categoria.id %}" class="list-group-item list-group-item-action">{{ categoria.nome }}</a>
            {% endfor %}
        </ul>
      </div>
{% endblock %}

conteudo/templates/conteudo/editar_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

conteudo/templates/conteudo/lista_categoria.html
{% extends "base.html" %}

{% load static %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="{% url 'conteudo:catalogo' %}">Meu Canal</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
				  <li class="nav-item active">
				    <a class="nav-link" href="{% url 'conteudo:catalogo' %}">Início <span class="sr-only">(current)</span></a>
				  </li>
	  			  <li class="nav-item">
				    <a class="nav-link" href="#">Séries</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href="#">Área Kids</a>
				  </li>
	  			  <li class="nav-item">
				    <a class="nav-link" href="#" type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">Categorias</a>
				  </li>
				</ul>
				<form class="form-inline my-2 my-lg-0 ml-auto">
				  <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Search">
				  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
				</form>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          Usuário
          			      <img class="rounded-circle" src="{% static 'projeto/images/user_male.png' %}" alt="Generic placeholder image" width="55" height="50">
				        </a>
				        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
				          <a class="dropdown-item" href="#">Minha Conta</a>
				          <a class="dropdown-item" href="#">Minha Lista</a>
				          <div class="dropdown-divider"></div>
				          <a class="dropdown-item" href="{% url 'pagina_inicial' %}">Logout</a>
				        </div>
			      	</li>
			  	</ul>
			</div>
		</div>
	</nav>
{%  endblock %}

{% block conteudo %}
    	<div class="container catalogo-container">
            <div class="selecao_videos row text-center">
                {% for video in videos %}
                    <div class="col-md-4 mb-2">
                        <div class="card">
                            <img class="card-img-top" src="{{video.capa}}" alt="{{ video.nome }}">
                            <div class="card-body">
                                <h5 class="card-title" data-toggle="tooltip" data-placement="top" title="{{ video.nome }}">{{ video.nome }}</h5>
                                <a href="{% url 'conteudo:exibir_video' id=video.id %}" type="button" class="btn btn-info btn-block">Assistir</a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="row">
                <div class="mx-auto">
                    {% if videos.has_other_pages %}
                    <nav aria-label="Page navigation example">
                      <ul class="pagination">
                        {% if videos.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ videos.previous_page_number }}">Anterior</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="">Anterior</a></li>
                        {% endif %}
                        {% for i in videos.paginator.page_range %}
                            {% if videos.number == i %}
                                <li class="page-item active"><a class="page-link" href="?page={{ videos.number }}">{{ i }} </a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if videos.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ videos.next_page_number }}">Proximo</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="">Proximo</a></li>
                        {% endif %}
                      </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>

	</div>
{% endblock %}

{% block modal-content %}
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Categorias</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group">
            {% for categoria in categorias %}
                <a href="{% url 'conteudo:lista_categoria' id=categoria.id %}" class="list-group-item list-group-item-action">{{ categoria.nome }}</a>
            {% endfor %}
        </ul>
      </div>
{% endblock %}

conteudo/templates/conteudo/player_video.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}Meu Canal - Video{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="{% url 'conteudo:catalogo' %}">Meu Canal</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
				  <li class="nav-item active">
				    <a class="nav-link" href="{% url 'conteudo:catalogo' %}">Início <span class="sr-only">(current)</span></a>
				  </li>
	  			  <li class="nav-item">
				    <a class="nav-link" href="#">Séries</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href="#">Área Kids</a>
				  </li>
	  			  <li class="nav-item">
				    <a class="nav-link" href="#" type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">Categorias</a>
				  </li>
				</ul>
				<form class="form-inline my-2 my-lg-0 ml-auto">
				  <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Search">
				  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
				</form>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          Usuário
          			      <img class="rounded-circle" src="{% static 'projeto/images/user_male.png' %}" alt="Generic placeholder image" width="55" height="50">
				        </a>
				        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
				          <a class="dropdown-item" href="#">Minha Conta</a>
				          <a class="dropdown-item" href="#">Minha Lista</a>
				          <div class="dropdown-divider"></div>
				          <a class="dropdown-item" href="{% url 'pagina_inicial' %}">Logout</a>
				        </div>
			      	</li>
			  	</ul>
			</div>
		</div>
	</nav>
{% endblock %}

{% block conteudo %}
    <div class="container pagina_video mb-5">
		<div class="row">
			<div class="col-md-8 mb-3">
				<video id="myVideo" height="100%" width="100%" controls="controls">
					<source src="/../../media/{{video.url}}" type="video/mp4">
					<object data="" width="320" height="230">
					</object>
				</video>
			</div>

			<div class="col-md-4 mb-3">
				<div id="accordion">
				  	<div class="card">
					    <div class="card-header" id="headingOne">
					      	<h5 class="mb-0">
					        	<button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" id="botaoComentario">
					          	Comentários:</button>
					      	</h5>
					    </div>

					    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
					      	<div class="card-body">
					      		<div class="container rolagem">
							        <form class="form-inline">
						        	  	<div class="form-group">
						        	  		<label for="inputComentario">Digite seu Comentário:</label>
										    <input type="text" id="inputComentario" class="form-control" placeholder="Digite aqui"/>
									  		<button type="submit" class="btn btn-primary"><span class="oi oi-circle-check"></span></button>
									  	</div>
									</form>
								  	<div class="form-group">
								  		<ul class="list-unstyled">
										  	<li class="media my-4">
											    <img class="mr-1" src="{% static 'projeto/images/user_icon.png' %}" alt="Generic placeholder image" width="64" height="64">
											    <div class="media-body">
											      <h5 class="mt-0 mb-3">Usuário 1</h5>
											      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
											    </div>
										  	</li>
										  	<li class="media my-4">
											    <img class="mr-1" src="{% static 'projeto/images/user_icon.png' %}" alt="Generic placeholder image" width="64" height="64">
											    <div class="media-body">
											      <h5 class="mt-0 mb-3">Usuário 2</h5>
											      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
											    </div>
										  	</li>
										</ul>
									</div>
								</div>
				        	</div>
				    	</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block modal-content %}
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Categorias</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group">
            {% for categoria in categorias %}
                <a href="{% url 'conteudo:lista_categoria' id=categoria.id %}" class="list-group-item list-group-item-action">{{ categoria.nome }}</a>
            {% endfor %}
        </ul>
      </div>
{% endblock %}

login/templates/login/pagina_login.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}Meu Canal - Login{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="{% url 'pagina_inicial' %}">Meu Canal</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
			  <li class="nav-item active">
			    <a class="nav-link" href="{% url 'pagina_inicial' %}">Início <span class="sr-only">(current)</span></a>
			  </li>
			</ul>
			</div>
		</div>
	</nav>
{% endblock %}

{% block conteudo %}
<div class="container mb-5">
		<div class="row">
			<div class="col-md-4 mx-auto mb-5 login">
				<h2> Entrar </h2>
				<form class="mb-5" action="{% url 'conteudo:catalogo' %}">
				  <div class="form-group">
				    <label for="email">Email</label>
				    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Digite seu Email">
				  </div>
				  <div class="form-group mb-5">
				    <label for="password">Senha</label>
				    <input type="password" class="form-control" id="password" placeholder="Digite sua senha">
				  </div>
				  <a href="#"> Esqueceu seu e-mail ou senha?</a>
				  <button type="submit" class="btn btn-primary btn-block">Entrar</button>
  				  <div class="form-check">
				    <input type="checkbox" class="form-check-input" id="exampleCheck1">
				    <label class="form-check-label" for="exampleCheck1">Lembre-se de mim</label>
				    <hr>
				  </div>
				  <div class="form-group">
				  	<a href="#">Conectar com o Facebook</a><br>
				  	Novo por aqui?<button type="button" class="btn btn-link" data-toggle="modal" data-target="#modal">Assine agora</button>
				  </div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}